#!/bin/bash

if [ -a /dev/$1 ]; then
	echo "sdcard present."
	umount /dev/${1}1
	umount /dev/${1}2
else
	echo "Please Insert sdcard."
	exit 1;
fi

echo "Fusing sdcard ..."
SD_BLKCNT=`cat /sys/block/$1/size`
#SD_BLKCNT=7773184
echo "sd_blkcnt=${SD_BLKCNT}"
#SD_SIZE=`expr ${SD_BLKCNT} \/ 2 \/ 1024`
SD_SIZE=$((${SD_BLKCNT}*512/1024))
echo "The total size of $1 is ${SD_SIZE}K."

UBOOT_BLKCNT=`expr 512 \* 1024 \/ 512`
SD_BL2_POS=$((${SD_BLKCNT}-1-1-${UBOOT_BLKCNT}))
SDHC_BL2_POS=$((${SD_BLKCNT}-1024-1-1-${UBOOT_BLKCNT}))
echo "sd_bl2_pos=$SD_BL2_POS, sdhc_bl2_pos=$SDHC_BL2_POS, uboot_blkcnt=$UBOOT_BLKCNT."

KERNEL_SIZE=5898240
KERNEL_BLKCNT=$((${KERNEL_SIZE}/512))
SD_KERNEL_POS=$((${SD_BL2_POS}-${KERNEL_BLKCNT}))
SDHC_KERNEL_POS=$((${SDHC_BL2_POS}-${KERNEL_BLKCNT}))
echo "sd_kernel_pos=$SD_KERNEL_POS, sdhc_kernel_pos=$SDHC_KERNEL_POS, kernel_size=$KERNEL_SIZE"

if [ "$SD_BLKCNT" -gt "4194304" ] ; then
	echo "fuse u-boot to sdhc"
#	dd if=/dev/zero of=/dev/$1 bs=512 seek=${SDHC_KERNEL_POS} count=$((${SD_BLKCNT}-${SDHC_KERNEL_POS}))
	dd if=u-boot-sd.bin of=/dev/$1 bs=512 seek=${SDHC_BL2_POS}
#	dd if=./zImage of=/dev/$1 bs=512 seek=${SDHC_KERNEL_POS}
else
	echo "fuse u-boot to sd"
	dd if=/dev/zero of=/dev/$1 bs=512 seek=${SD_KERNEL_POS} count=$((${SD_BLKCNT}-${SD_KERNEL_POS}))
	dd if=u-boot-sd.bin of=/dev/$1 bs=512 seek=${SD_BL2_POS}
	dd if=./zImage of=/dev/$1 bs=512 seek=${SD_KERNEL_POS}
fi

sync
