#!/bin/bash

echo "@@@@@@@@@@@@@@@@@@@@@@@ $(pwd)"
rm -f u-boot-sd*

# padding to 512k u-boot
cat u-boot.bin >> u-boot-2x.bin
cat u-boot.bin >> u-boot-2x.bin
cat u-boot.bin >> u-boot-2x.bin

# make BL2 (504k)
split -d -a 1 -b 504k u-boot-2x.bin u-boot-504k.bin
mv u-boot-504k.bin0 u-boot-504k.bin

# test
#split -d -a 1 -b 248k u-boot-2x.bin u-boot-248k.bin
#mv u-boot-248k.bin0 u-boot-248k.bin

# concat the BL1 behind of BL2
cat u-boot-504k.bin > u-boot-sd.bin
#cat mmc_spl/u-boot-spl-8k.bin >> u-boot-sd.bin
cat spl/u-boot-spl.bin >> u-boot-sd.bin

# chmod
chmod 777 u-boot-sd.bin

# remove temp files
rm -f u-boot-2x.bin
rm -f u-boot-504k*
