#!/bin/bash

set -e

spl=
uboot=
spl_size=
page_size=
outdir=

usage ()
{
	echo "Usage:"
	echo -e "\t--spl u-boot-spl.bin"
	echo -e "\t--uboot u-boot.bin"
	echo -e "\t--spl-size size"
	echo -e "\t--page-size size"
	echo -e "\t--outdir dir"
}

while true
do
	case "$1" in
		--spl)
			spl=$2
			shift 2
			;;
		--uboot)
			uboot=$2
			shift 2
			;;
		--spl-size)
			spl_size=$2
			shift 2
			;;
		--page-size)
			page_size=$2
			shift 2
			;;
		--outdir)
			outdir=$2
			shift 2
			;;
		*)
			break
			;;
	esac
done

if [[ -z ${spl} ]] || [[ -z ${uboot} ]] || \
   [[ -z ${spl_size} ]] || [[ -z ${page_size} ]]
then
	   usage
	   exit 1
fi

cp -fv ${spl} ${outdir}/spl.bin

dd if=/dev/zero bs=512K count=1 2>/dev/null | tr '\0' '\377' > ${outdir}/0xff.bin

# stage1: 10k
cat ${outdir}/spl.bin > ${outdir}/stage1.bin
cat ${outdir}/0xff.bin >> ${outdir}/stage1.bin
dd if=${outdir}/stage1.bin of=${outdir}/stage1.bin.tmp \
	bs=$((${spl_size}+${page_size})) count=1 2>/dev/null
mv ${outdir}/stage1.bin.tmp ${outdir}/stage1.bin

# stage2: 504k
cat ${uboot} > ${outdir}/stage2.bin
cat ${outdir}/0xff.bin >> ${outdir}/stage2.bin
dd if=${outdir}/stage2.bin of=${outdir}/stage2.bin.tmp bs=504K count=1 2>/dev/null
mv ${outdir}/stage2.bin.tmp ${outdir}/stage2.bin

# stage3: 8k
dd if=${outdir}/stage1.bin of=${outdir}/stage3.bin bs=${spl_size} count=1 2>/dev/null

cat ${outdir}/stage{1,2,3}.bin > ${outdir}/u-boot-spl.bin

rm -f ${outdir}/{spl,0xff,stage*}.bin
